/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavText: typeof import('bootstrap-vue-next/components/BNav')['BNavText']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    ChatNavBar: typeof import('./src/components/ChatNavBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBiActivity: typeof import('~icons/bi/activity')['default']
    ILucideLogOut: typeof import('~icons/lucide/log-out')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MessageForm: typeof import('./src/components/MessageForm.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    RoomList: typeof import('./src/components/RoomList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./src/components/UserList.vue')['default']
  }
}
